version: '3'

services:
    laravelapp:
        container_name: m2digital
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./.docker/nginx/conf.d/default.conf/:/etc/nginx/conf.d/default.conf
            - ./:/usr/share/nginx
        depends_on:
            - postgres
        networks:
            - networkis
        links:
            - postgres
            
    postgres:
        container_name: m2db
        image: 'postgres'
        ports:
            - "5432:5432"
        #volumes:
        #    - ./postgres:/var/lib/postgresql/data
        environment:
            TZ: "America/Sao_Paulo"
            PGTZ: "America/Sao_Paulo"
            POSTGRES_DB: "m2digital"
            POSTGRES_USER: "m2digital"
            POSTGRES_PASSWORD: "m2digital"
        networks:
            - networkis
            
networks: 
    networkis:
        driver: bridge